### ISSUE TITLE
problems installing npm packages

### ISSUE THREAD

**Issue by vangalvin** [IoT-nxt/prototype#189]
Following the guide and trying to install on a Windows 7 64bit platform I installed Node.js then proceeded to install the packages using npm however there seems to be huge issues with the dependancies.

```
npm WARN css-loader@2.1.1 requires a peer of webpack@^4.0.0 but none is installe
d. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of bufferutil@^4.0.0 but none is inst
alled. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of erlpack@discordapp/erlpack but non
e is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of libsodium-wrappers@^0.7.3 but none
 is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of node-opus@^0.2.7 but none is insta
lled. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of opusscript@^0.0.6 but none is inst
alled. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of sodium@^2.0.3 but none is installe
d. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of @discordjs/uws@^10.149.0 but none
is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.7.0 requires a peer of webpack@^4.0.0 but none
 is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.8.0 requires a peer of webpack@^4.0.0 but none is
installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
```

even upgrading the dependancies seems to result in other parts of the system not running.

The closest I managed to get was resulted in this error.
```
Error: Cannot find module 'scrypt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\andrew\prototype\build\accounts.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Then after installing Scrypt all the package dependancies broke again.

**Comment by fluentart** [comment]
Try with node version 11.15.0, I found that solves the build issue.

The plan is to replace the external scrypt module with the new built in scrypt crypto module which should resolve this build issue.

**Comment by DeepaSoul** [comment]
If you are using windows, and node doesn't help, try following the steps of installing node-gyp, you might also need the windows build tools which you will find on the node-gyp installation guide.

**Comment by vangalvin** [comment]
I will give that a try, thanks :) Yes I have Python installed and let you know how that goes.
