### ISSUE TITLE
Fresh pi4 install , mongoose / mongodb issues 

### ISSUE THREAD

**Issue by tobievii** [IoT-nxt/prototype#192]
> prototype@5.1.0 watchserver /home/pi/prototype
> nodemon build/server/main.js

[nodemon] 1.19.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] starting `node build/server/main.js`
2019-09-29T08:20:00.436Z error		2481 could not read iotconfig.json Error: ENOENT: no such file or directory, open '/home/pi/prototype/iotconfig.json'	
2019-09-29T08:20:00.783Z info		2481 process start	
2019-09-29T08:20:00.787Z info		2481 cluster isMaster	
2019-09-29T08:20:00.787Z info		2481 cluster forking	
2019-09-29T08:20:00.818Z info		2481 cluster forking	
2019-09-29T08:20:00.838Z info		2481 cluster forking	
2019-09-29T08:20:00.873Z info		2481 cluster forking	
(node:2481) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
{ MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoError: Server at localhost:27017 reports maximum wire version 0, but this version of the Node.js Driver requires at least 2 (MongoDB 2.6)]
    at Pool.<anonymous> (/home/pi/prototype/node_modules/mongoose/node_modules/mongodb/lib/core/topologies/server.js:431:11)
    at Pool.emit (events.js:198:13)
    at Pool.EventEmitter.emit (domain.js:448:20)
    at connect (/home/pi/prototype/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:580:14)
    at callback (/home/pi/prototype/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:109:5)
    at runCommand (/home/pi/prototype/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:140:7)
    at Connection.messageHandler (/home/pi/prototype/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:334:5)
    at Connection.emit (events.js:198:13)
    at Connection.EventEmitter.emit (domain.js:448:20)
    at processMessage (/home/pi/prototype/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:364:10)
    at Socket.<anonymous> (/home/pi/prototype/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:533:15)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
2019-09-29T08:20:03.754Z error		2481 mongoose db connect error

**Comment by tobievii** [comment]
Mongodb is installed and working fine , seems like another issue with versions, note , you cannot update mongodb version from 2.4 as it's a 32bit system , 64bit for pi not existent

**Comment by rvdende** [comment]
The location of the config file was moved up to the root of the project.
Please copy your old config file to where you cloned the repo. This should enable it to find the config file.

Also, there was a slight change in how mongodb config urls are parsed and used from config files. Please see https://github.com/IoT-nxt/prototype/blob/dev/iotconfig_sample.json for example.

**Comment by rvdende** [comment]
Another possibilty is that you did not read the 5.0 to 5.1 migration notes. https://github.com/IoT-nxt/prototype#50-to-51-migration-notes regarding mongo setup

**Comment by tobievii** [comment]
Hi have read this thank you ,

Config not an issue , but still get mongoose issue , cannot replica set
mongodb 2.4 32bit , hence the problem ...

**Comment by rvdende** [comment]
According to this guy it should work: https://medium.com/@jamesjudd_21057/mongodb-setting-up-a-three-member-replica-set-on-raspberry-pis-9c76db58afe9

**Comment by tobievii** [comment]
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoError: Server at localhost:27017 reports maximum wire version 0, but this version of the Node.js Driver requires at least 2 (MongoDB 2.6)]

**Comment by tobievii** [comment]
Replica is fine but the driver as first reported is issue
